version: '3'
services:
  tigergraph:
    image: docker.tigergraph.com/tigergraph:latest
    container_name: tigergraph
    ports: 
      - "14022:22"
      - "9000:9000"
      - "14240:14240"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - "/data:/home/tigergraph/mydata"
      - "~/TigerGraph/name.csv:/home/tigergraph/name.csv"
      - "~/TigerGraph/friends.csv:/home/tigergraph/friends.csv"
      - "~/TigerGraph/mygraph.gsql:/home/tigergraph/mygraph.gsql"

